### ISSUE TITLE
Tornadoredis issue for docker test

### ISSUE THREAD

**Issue by Mario2334** [Deathangel908/djangochat#17]
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornadoredis/client.py", line 250, in __del__
  File "/usr/lib/python3.6/site-packages/tornadoredis/client.py", line 279, in __getattribute__
TypeError: isinstance() arg 2 must be a type or tuple of types

**Comment by akoidan** [comment]
@Mario2334 please provide steps to reproduce the issue.

**Comment by akoidan** [comment]
Fixed in new docker image
